#!/usr/bin/env bash
#########################################################################
# BTRFS Auto Snapshotter (Hourly)                                       #
#                                                                       #
#   Automatically takes snapshots of / into                             #
#       /snaps/daily/YYYY-mm-dd/HH                                      #
#   every hour.                                                         #
#                                                                       #
# Part of HopeSeekr's BashScripts Collection                            #
# https://github.com/hopeseekr/BashScripts/                             #
#                                                                       #
# Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>          #
# GPG Fingerprint: 4BF8 2613 1C34 87AC D28F  2AD8 EB24 A91D D612 5690   #
#                                                                       #
# License: Creative Commons Attribution v4.0 International              #
#########################################################################

# @see https://serverfault.com/a/37836/56309
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Error: You *MUST* run this as sudo or root!"
    echo ""
    exit 99
fi

DATE=$(date +"%Y-%m-%d")
HOUR=$(date +"%H")

mkdir -p /snaps/daily

if [[ ! -d "/snaps/daily" ]]; then
    mkdir /snaps/daily
fi

if [[ ! -d "/snaps/daily/${DATE}" ]]; then
    btrfs subvolume snapshot / /snaps/daily/${DATE}
fi

if [[ ! -d "/snaps/code" ]]; then
    mkdir /snaps/code
fi

if [[ ! -d "/snaps/code/${DATE}" ]]; then
    btrfs subvolume snapshot /code /snaps/code/${DATE}
fi


btrfs subvolume snapshot /code /snaps/code/${DATE}/${HOUR}
