#!/usr/bin/env bash
#########################################################################
# Show Active WIFI Password                                             #
#                                                                       #
#   Shows the Wi-Fi password for the currently connected AP.            #
#                                                                       #
# Part of HopeSeekr's BashScripts Collection                            #
# https://github.com/hopeseekr/BashScripts/                             #
#                                                                       #
# Copyright © 2025 Theodore R. Smith <theodore@phpexperts.pro>          #
# GPG Fingerprint: 4BF8 2613 1C34 87AC D28F  2AD8 EB24 A91D D612 5690   #
#                                                                       #
# License: Creative Commons Attribution v4.0 International              #
#########################################################################

nmcli dev wifi show-password
